spring:
   data:
      mongodb:
         uri: "mongodb+srv://root:sapassword@serviceapiktpm.ist0v2k.mongodb.net/?retryWrites=true&w=majority"
         database: StoreCake
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url: 
         defaultZone: http://localhost:8761/eureka/
   instance: 
      hostname: localhost       

